export interface StockEntry {
  symbol: string;
  name: string;
}

export const topStocks: StockEntry[] = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "GOOGL", name: "Alphabet Inc." },
  { symbol: "META", name: "Meta Platforms Inc." },
  { symbol: "TSLA", name: "Tesla Inc." },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc." },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "UNH", name: "UnitedHealth Group Inc." },
  { symbol: "XOM", name: "Exxon Mobil Corporation" },
  { symbol: "LLY", name: "Eli Lilly and Company" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "MA", name: "Mastercard Inc." },
  { symbol: "PG", name: "Procter & Gamble Co." },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "HD", name: "Home Depot Inc." },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "MRK", name: "Merck & Co. Inc." },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "COST", name: "Costco Wholesale Corporation" },
  { symbol: "PEP", name: "PepsiCo Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "CSCO", name: "Cisco Systems Inc." },
  { symbol: "ACN", name: "Accenture plc" },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "NFLX", name: "Netflix Inc." },
  { symbol: "CRM", name: "Salesforce Inc." },
  { symbol: "BAC", name: "Bank of America Corporation" },
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "WFC", name: "Wells Fargo & Company" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc." },
  { symbol: "TXN", name: "Texas Instruments Inc." },
  { symbol: "QCOM", name: "Qualcomm Inc." },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "NEE", name: "NextEra Energy Inc." },
  { symbol: "PM", name: "Philip Morris International Inc." },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company" },
  { symbol: "RTX", name: "RTX Corporation" },
  { symbol: "LOW", name: "Lowe's Companies Inc." },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "HON", name: "Honeywell International Inc." },
  { symbol: "UNP", name: "Union Pacific Corporation" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "GS", name: "Goldman Sachs Group Inc." },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "IBM", name: "International Business Machines Corp." },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "BX", name: "Blackstone Inc." },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "ISRG", name: "Intuitive Surgical Inc." },
  { symbol: "SPGI", name: "S&P Global Inc." },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "AXP", name: "American Express Company" },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "BLK", name: "BlackRock Inc." },
  { symbol: "CI", name: "The Cigna Group" },
  { symbol: "GILD", name: "Gilead Sciences Inc." },
  { symbol: "ADI", name: "Analog Devices Inc." },
  { symbol: "LRCX", name: "Lam Research Corporation" },
  { symbol: "NOW", name: "ServiceNow Inc." },
  { symbol: "MO", name: "Altria Group Inc." },
  { symbol: "SYK", name: "Stryker Corporation" },
  { symbol: "TJX", name: "TJX Companies Inc." },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc." },
  { symbol: "CB", name: "Chubb Limited" },
  { symbol: "SO", name: "Southern Company" },
  { symbol: "ELV", name: "Elevance Health Inc." },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc." },
  { symbol: "SCHW", name: "Charles Schwab Corporation" },
  { symbol: "ZTS", name: "Zoetis Inc." },
  { symbol: "DUK", name: "Duke Energy Corporation" },
  { symbol: "BSX", name: "Boston Scientific Corporation" },
  { symbol: "NOC", name: "Northrop Grumman Corporation" },
  { symbol: "PANW", name: "Palo Alto Networks Inc." },
  { symbol: "MMC", name: "Marsh & McLennan Companies Inc." },
  { symbol: "ICE", name: "Intercontinental Exchange Inc." },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "SHW", name: "Sherwin-Williams Company" },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "PLD", name: "Prologis Inc." },
  { symbol: "FCX", name: "Freeport-McMoRan Inc." },
  { symbol: "ITW", name: "Illinois Tool Works Inc." },
  { symbol: "KLAC", name: "KLA Corporation" },
  { symbol: "PH", name: "Parker-Hannifin Corporation" },
  { symbol: "CME", name: "CME Group Inc." },
  { symbol: "EQIX", name: "Equinix Inc." },
  { symbol: "AON", name: "Aon plc" },
  { symbol: "MU", name: "Micron Technology Inc." },
  { symbol: "NXPI", name: "NXP Semiconductors N.V." },
  { symbol: "MCHP", name: "Microchip Technology Inc." },
  { symbol: "APH", name: "Amphenol Corporation" },
  { symbol: "WM", name: "Waste Management Inc." },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "ECL", name: "Ecolab Inc." },
  { symbol: "NSC", name: "Norfolk Southern Corporation" },
  { symbol: "EMR", name: "Emerson Electric Co." },
  { symbol: "FDX", name: "FedEx Corporation" },
  { symbol: "APD", name: "Air Products and Chemicals Inc." },
  { symbol: "EW", name: "Edwards Lifesciences Corporation" },
  { symbol: "MCO", name: "Moody's Corporation" },
  { symbol: "CDNS", name: "Cadence Design Systems Inc." },
  { symbol: "SNPS", name: "Synopsys Inc." },
  { symbol: "ROP", name: "Roper Technologies Inc." },
  { symbol: "IDXX", name: "IDEXX Laboratories Inc." },
  { symbol: "CTAS", name: "Cintas Corporation" },
  { symbol: "HUM", name: "Humana Inc." },
  { symbol: "DOW", name: "Dow Inc." },
  { symbol: "OXY", name: "Occidental Petroleum Corporation" },
  { symbol: "D", name: "Dominion Energy Inc." },
  { symbol: "AIG", name: "American International Group Inc." },
  { symbol: "WELL", name: "Welltower Inc." },
  { symbol: "DXCM", name: "DexCom Inc." },
  { symbol: "CARR", name: "Carrier Global Corporation" },
  { symbol: "IQV", name: "IQVIA Holdings Inc." },
  { symbol: "LMT", name: "Lockheed Martin Corporation" },
  { symbol: "GD", name: "General Dynamics Corporation" },
  { symbol: "BA", name: "Boeing Company" },
  { symbol: "UBER", name: "Uber Technologies Inc." },
  { symbol: "ABNB", name: "Airbnb Inc." },
  { symbol: "PYPL", name: "PayPal Holdings Inc." },
  { symbol: "COIN", name: "Coinbase Global Inc." },
  { symbol: "PLTR", name: "Palantir Technologies Inc." },
  { symbol: "RIVN", name: "Rivian Automotive Inc." },
  { symbol: "NIO", name: "NIO Inc." },
  { symbol: "BIDU", name: "Baidu Inc." },
  { symbol: "BABA", name: "Alibaba Group Holding Limited" },
  { symbol: "MELI", name: "MercadoLibre Inc." },
  { symbol: "SPOT", name: "Spotify Technology S.A." },
  { symbol: "DASH", name: "DoorDash Inc." },
  { symbol: "RBLX", name: "Roblox Corporation" },
  { symbol: "SNAP", name: "Snap Inc." },
  { symbol: "PINS", name: "Pinterest Inc." },
  { symbol: "SQ", name: "Block Inc." },
  { symbol: "HOOD", name: "Robinhood Markets Inc." },
  { symbol: "LYFT", name: "Lyft Inc." },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc." },
  { symbol: "ZM", name: "Zoom Video Communications Inc." },
  { symbol: "DOCU", name: "DocuSign Inc." },
  { symbol: "OKTA", name: "Okta Inc." },
  { symbol: "NET", name: "Cloudflare Inc." },
  { symbol: "DDOG", name: "Datadog Inc." },
  { symbol: "SNOW", name: "Snowflake Inc." },
];
